### ISSUE TITLE
add support for jquery 3

### ISSUE THREAD

**Issue by Mati365** [OwlCarousel2/OwlCarousel2#1466]
it is not working with jquery 3

**Comment by nebrot** [comment]
Do you use latest version? Should be fixed in https://github.com/OwlCarousel2/OwlCarousel2/releases/tag/2.1.6

**Comment by CracyCrazz** [comment]
As nebrot stated in the previous comment, it should definitly be fixed in the latest version. Just run a bower update and you should be fine, if not feel free to post a JSFiddle with an example.

**Comment by Mati365** [comment]
i'm installing owl.carousel 2.1.4, only this one is available in npm

**Comment by kraymond70** [comment]
Hi,
I am using JQuery 3.1.0 and I still have a problem with Owl Carousel.

<img width="1024" alt="capture d ecran 2016-07-21 a 07 19 10" src="https://cloud.githubusercontent.com/assets/1266755/17013009/88d75b7c-4f13-11e6-8e2b-1da1409a8667.png">

**Comment by Mati365** [comment]
Did you install owl.carousel from npm?

**Comment by kraymond70** [comment]
I installed it from bower.

**Comment by kraymond70** [comment]
Some updates on this ?

**Comment by daviddeutsch** [comment]
Fixed in 2.2.0. :confetti_ball:
