### ISSUE TITLE
Grabbing hand image doesn't work sometimes (mostly).

### ISSUE THREAD

**Issue by Bram-Zijp** [OwlCarousel2/OwlCarousel2#1597]
The grabbing hand doesn't appear mostly in Google Chrome (latest version) didn't test other browsers but i can't believe this would be browser dependant judging by the quality of Chrome.

Edit: 
Funny i spoke about Chrome and it's quality as it seems to be the only browser with cursor issues.

**Comment by hello-jason** [comment]
Works fine for me, latest version of Chrome (54). Are you still having issues?

![image](https://cloud.githubusercontent.com/assets/1406213/19665202/846eb972-9a09-11e6-8c9a-cee6ed618884.png)

**Comment by Bram-Zijp** [comment]
This issue is resolved by the Chrome Browser.

**Comment by monecchi** [comment]
I'm using Chrome version (56.0.2924.87) (64-bit) on Mac and the issue persists.

**Comment by demogorgorn** [comment]
The hand cursor disapears on other page's elements after using the dots nav of the owl carousel.

**Comment by hello-jason** [comment]
Looks like they switched to a move cursor, rather than a custom one.

Chrome 57, Windows:
![image](https://cloud.githubusercontent.com/assets/1406213/24465995/d7ba6410-1474-11e7-812d-ac7240bad50c.png)
