### ISSUE TITLE
Blured text problem

### ISSUE THREAD

**Issue by Jhonb** [OwlCarousel2/OwlCarousel2#162]
Hi guys,

I have a little problem using OWL carousel 2. You can see it in action right here:
http://www.serialkreative.be/jhon/index.html

The text of the 2 next news are blured... Any solution?

Thanks a lot,

Jhon

**Comment by tomaszbujnowicz** [comment]
An easy fix that worked for me.

Find .owl-carousel .owl-item in the stylesheet and add 
-webkit-perspective: 1000;
 
It did the trick. It's a standard fix for translate3d(), scale() and any other css3 transform animations.

**Comment by jhongstore** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

dcjae@naver.com 님께 보내신 메일 <Re: [OwlCarousel2] Blured text problem (#162)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by oskolsky** [comment]
@tomaszbujnowicz good decision, no need to patch js

**Comment by Anydog** [comment]
yeah ...  great carousel but that blur is a killer ...
I found out that -webkit-perspective: 1000px doesn't work for me, text is still blurred ... 
The @HitArrowLegend solution with toFixed(0) is working, but I believe, with some performance loss.

Any how the translate3d(-1373.665 px, 0px, 0px); in my browser (Chrome / Win 8.1 - which I believe is very common combination ) is now  translate3d(-1373 px, 0px, 0px); and it's ok.

Something to fix ... Maybe somewhere sooner in code to apply toFixed(0) to coordinate var.

Cheers

**Comment by eplehans** [comment]
I have the same problem. -webkit-perspective: 1000; didn't do it for me.

**Comment by eplehans** [comment]
It may be a small hack, but I fixed it by going in to owl.carousel.js and changed translate3d to translate.

transform: 'translate(' + coordinate + 'px' + ',0px)'
instead of..
transform: 'translate3d(' + coordinate + 'px' + ',0px, 0px)'

**Comment by adelwafa** [comment]
@eplehans U R Amazing, About 18 Hour Looking For A solution for these problem and finally  ur solution saved my tomorrow, Thank u bro.

**Comment by matheusazzi** [comment]
Isn't there a fix for it yet? As I see `Math.round(coordinate)` is the best solution while?

**Comment by godzik** [comment]
maybe it sounds funny, but removing 'center: true' option worked in my case :D
![blur-notblur](https://cloud.githubusercontent.com/assets/7449380/10783188/8b3860f0-7d5e-11e5-9b59-dd00566a5615.jpg)

**Comment by morteza-gho** [comment]
hi, use margin to solve this problem.

**Comment by wbruno** [comment]
they solved at `v2.1.1`

**Comment by jack-fdrv** [comment]
Where we can get 2.1.1?

**Comment by jack-fdrv** [comment]
It may be a small hack, but I fixed it by going in to owl.carousel.js and changed translate3d to translate.

transform: 'translate(' + coordinate + 'px' + ',0px)'
instead of..
transform: 'translate3d(' + coordinate + 'px' + ',0px, 0px)'

- it works but now it jumping.

**Comment by jack-fdrv** [comment]
transform: 'translate3d(' + Math.round(coordinate) + 'px' + ',0px, 0px)',
works perfect, thnx

**Comment by tonykiefer** [comment]
If it has been released you can get it from git...currently 2.0 is beta

**Comment by rivarchi9** [comment]
Hi! The problem has been solved when I deleted the feature `webkit-backface-visibility: hidden;` in file **owl.carousel.css**. And raplace `transform: 'translate3d(' + coordinate + 'px' + ',0px, 0px)'` on `transform: 'translate(' + coordinate + 'px' + ',0px)'` to file **owl.carousel.js**. I think lots of people have problem with it.

**Comment by stribJamieHutt** [comment]
@rivarchi9 your solution worked brilliantly. Saved my butt this morning.

**Comment by andreich1980** [comment]
I use "owl.carousel": "^2.2.0" and still have the problem, not with text but with images (they look pixilated).
Thanks, @rivarchi9

**Comment by nouoxu** [comment]
This is a well-known WebKit/Chrome rendering issue with translate3d and sub-pixel values. The solutions mentioned in the comments (using `Math.round()` or switching to `translate` instead of `translate3d`) are the main workarounds.

For those still experiencing this issue, here's a summary of the fixes that work:

1. **Use Math.round()**: Change `translate3d(coordinate + 'px', 0px, 0px)` to `translate3d(Math.round(coordinate) + 'px', 0px, 0px)`

2. **Switch to translate**: Replace `translate3d` with `translate` (may affect hardware acceleration)

3. **CSS fix**: Add `-webkit-perspective: 1000px` to the carousel container

Note: This issue was reportedly fixed in version 2.1.1. If you're using an older version, consider upgrading.

For modern alternatives, check out [Swiper](https://swiperjs.com) or [Glide.js](https://glidejs.com) which have better maintained codebases.
