### ISSUE TITLE
autoplay stops working after tab switch

### ISSUE THREAD

**Issue by unaor** [OwlCarousel2/OwlCarousel2#1727]
Im using version 2.2.0 and when switching tab, the images do no autoplay

here is my code

`  $('#clients').owlCarousel({
        center: true,
        items:4,
        loop:true,
        autoplay: true,
        autoplayTimeout: 1000,
        margin:10
    });
`

**Comment by ocvninfo** [comment]
Same issue. I must drag slide to active autoplay again.

**Comment by ChamesBont** [comment]
Same Problem. Autoplay stops after tab switch.

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.

**Comment by ocvninfo** [comment]
This is important!
Can anyone help?

**Comment by unaor** [comment]
i dont think  i have privileges to reopen #1727

**Comment by pascalporedda** [comment]
Okay, confirmed.

**Comment by jstneti01** [comment]
Btw same thing happens when autoplayHoverPause is set to true. After hovering over, it stops the autoplay. To activate autoplay again I must drag the slide.

**Comment by ocvninfo** [comment]
@jstneti01 Exactly like that.

**Comment by unaor** [comment]
any news?

**Comment by Nedgeva** [comment]
Seems like reason of this strange autoplay behaviour lies in 'owl.autoplay.js' file in 'Autoplay.prototype._getNextTimeout' function. Everytime '_getNextTimeout' get called it checks internal state and document visibility ('document.hidden'). My guess is that removing unnecessary check for document.hidden would solve this problem.

**Comment by alalfakawma** [comment]
yes, can't please clients with autoplay stopping randomly

**Comment by unaor** [comment]
@Nedgeva solution works for me, i commented this part for the time being

**Comment by rushi-regur** [comment]
This didn't worked in my case

**Comment by Nedgeva** [comment]
@rushi-regur comment out whole statement as following
`/*if (this._paused || this._core.is('busy') || this._core.is('interacting') || document.hidden) {return;}*/`

That should work.

**Comment by rushi-regur** [comment]
@Nedgeva Thanks for your prompt response.

No luck again... 
BTW I am using Owl Carousel 2.2.1 in Chrome browser. Also tried it with Mozilla, but didn't worked.

**Comment by unaor** [comment]
to me it works, make sure you're loading the version you have edited and not the minified version

**Comment by rushi-regur** [comment]
@Nedgeva  @unaor @nickicool Thanks for your help! :)

**Comment by chiragunadkat78** [comment]
@nickicool Thanks, This works for me.

**Comment by coudrak** [comment]
@nickicool Not working for the mousehover for me... it stops and after need to do drag to start again.
But if fixed the tab switch.

**Comment by webns** [comment]
Have this problem too. I found out that problem is the timeout won't start after hover or switch tab. My solution is next
`if (this._paused || this._core.is('busy') || this._core.is('interacting') || document.hidden) {
    this._setAutoPlayInterval();
    return;
}`
It's works well for me, but be carefully :)

**Comment by tdecaluwe** [comment]
I'll try to shed some light on why you're seeing this and various other bugs.

The problems you're seeing we're unintentionally introduced by commit a062b49c900f20c8b67cf954040e49d642816ef2. In this commit the autoplay plugin migrated the `setInterval` call to chained `setTimeout` calls. The `setTimeout` chain is introduced by this event handler (that you'll find in the same commit):

```javascript
'changed.owl.carousel': $.proxy(function(e) {
    if (e.namespace && e.property.name === 'position') {
        //console.log('play?', e);
        if (this._core.settings.autoplay) {
            this._setAutoPlayInterval();
        }
    }
}, this)
```

The `position` property is changed by the animation which in turn triggers the next timeout. However, in certain cases, the animation is suppressed. These cases are governed by this lnie in the source code:

```javascript
if (this._paused || this._core.is('busy') || this._core.is('interacting') || document.hidden) {
```

If any of these are true the animation will not take place and the `setTimeout` chain will be broken. This is the real problem you want to solve. So if you wanted a quick fix you could just use the below code instead of the event listener:

```javascript
Autoplay.prototype._getNextTimeout = function(timeout, speed) {
    if ( this._timeout ) {
        window.clearTimeout(this._timeout);
    }
    return window.setTimeout($.proxy(function() {
        this._setAutoPlayInterval(timeout, speed);
        if (this._paused || this._core.is('busy') || this._core.is('interacting') || document.hidden) {
            return;
        }
        this._core.next(speed || this._core.settings.autoplaySpeed);
    }, this), timeout || this._core.settings.autoplayTimeout);
};
```

The reason the original author used a different approach can be found in issue #993. To solve both issues and a bunch of others I proposed PR #1942.

I

**Comment by daviddeutsch** [comment]
See #1942

**Comment by rajemahendra21** [comment]
@Nedgeva Thnx its working...

**Comment by cerensimsek1984** [comment]
@nickicool Thanks its works fine.
AutoplayHoverPause: true, is working but when mouse leave hover, it s not working again. Any idea?

**Comment by tdecaluwe** [comment]
Which version did you use? Could you provide a jsfiddle example?

**Comment by cerensimsek1984** [comment]
Owl Carousel v2.2.1 and jQuery v2.1.1 
`if (this._paused 
// || this._core.is('busy') 
|| this._core.is('interacting')
// || document.hidden
) {return;}`
this is working for "autoplay stops working after tab switch" but AutoplayHoverPause: true, is not working when mouse leave hover.

**Comment by dhullsumit** [comment]
@nickicool thanks, now working with tab switch.

**Comment by got3nks** [comment]
I'm having the same issue. Has the fix been merged yet?

**Comment by ExillustX** [comment]
@got3nks It should be fixed in this [version](https://github.com/OwlCarousel2/OwlCarousel2/archive/develop.zip).

**Comment by Ghost180195** [comment]
Was this bug fixed in version 2.3.2?

**Comment by cheaDalin** [comment]
I also have the same problem with 2.2.0 version so that I decide to change to use 2.3.4 version, yeah It is worked for me right now

**Comment by ranjudhk** [comment]
This particular error remains on version 2.2.1 BUT it's fixed on the latest version 2.3.4
So, Please update the owl.carousel.js or owl.carousel.min.js
Enjoy the carousel, Great Thanks!!
