### ISSUE TITLE
Problem after install owl.carousel

### ISSUE THREAD

**Issue by eduardocintra** [OwlCarousel2/OwlCarousel2#2422]
I'm following the steps of Quick start but when I run:

"npm run start" or "npm run build" I get a error:

```
ERROR in ./node_modules/owl.carousel/dist/assets/owl.carousel.css 9:0
Module parse failed: Unexpected token (9:0)
You may need an appropriate loader to handle this file type.
|  *  Owl Carousel - Core
|  */
> .owl-carousel {
|   display: none;
|   width: 100%;
 @ ./src/index.js 7:0-52
```
What did I do?

1 - npm install --save owl.carousel
2 - Add jQuery via the "webpack.ProvidePlugin" to my webpack configuration

```
const HtmlWebPackPlugin = require("html-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const webpack = require('webpack');
module.exports = {
  module: {
    rules: [

      {
        test: /\.html$/,
        use: [
          {
            loader: "html-loader",
            options: { minimize: true }
          }
        ]
      },
    {
        test: /\.(png|jpe?g)/i,
        use: [
          {
            loader: "url-loader",
            options: {
              name: "./img/[name].[ext]",
              limit: 10000
            }
          },
          {
            loader: "img-loader"
          }
        ]
      },
      {
        test: /\.(scss)$/,
        use: [
          MiniCssExtractPlugin.loader,
          "css-loader",
          "postcss-loader",
          "sass-loader"
        ]
      }
    ]
  },
  plugins: [
     new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      'window.jQuery': 'jquery'
    }),
    new HtmlWebPackPlugin({
      template: "./src/index.html",
      filename: "./index.html"
    }),
    new MiniCssExtractPlugin({
      filename: "[name].css",
      chunkFilename: "[id].css"
    })
  ]
};
```
3 - Loaded the required stylesheet and JS in my index.js

```
import 'bootstrap';
import './scss/app.scss';
import 'owl.carousel/dist/assets/owl.carousel.css';
import 'owl.carousel';
```

**Comment by caraboides** [comment]
I have the same issue

**Comment by 0x7061** [comment]
Same issue.

**Comment by 0x7061** [comment]
Resolved it, please don't forget to add your css loader to the webpack config. (scss alone doesn't do anything, because you are including a raw css file)

**Comment by radonichn** [comment]
Helped, thanks!

**Comment by ghost** [comment]
**I still experience this issue** and I have woking css loader. Webpack 4.
